language: python
python:
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt
before_deploy:
  - pip install travis-wait-improved
deploy:
    - script: pytest
       - python tests.py
       - travis-wait-improved --timeout 5m echo "test"
       - echo $!
