language: python
python:
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt
script:
   - python tests.py
   - travis-wait-improved --timeout 2m sleep 121
   - $pid_var =  $!
   - echo $pid_var
